services:
  panager:
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    command: uv run watchfiles "python -m panager.bot.client" src

  api:
    volumes:
      - ./src:/app/src
    command: uv run uvicorn panager.api.main:app --host 0.0.0.0 --port 8000 --reload
